name: shumanbeans-wedding
services:
  - name: web
    source_dir: .
    github:
      repo: skylerahuman/shumanbeans
      branch: main
      deploy_on_push: true
    build_command: NPM_CONFIG_PRODUCTION=false npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_SHEET_ID
        value: SET_IN_DO_CONSOLE
      - key: GOOGLE_CLIENT_EMAIL  
        value: SET_IN_DO_CONSOLE
      - key: GOOGLE_PRIVATE_KEY
        value: SET_IN_DO_CONSOLE
      - key: RESEND_API_KEY
        value: SET_IN_DO_CONSOLE
      - key: FROM_EMAIL
        value: SET_IN_DO_CONSOLE
